# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - release
cache: packages

r_github_packages: r-lib/pkgdown

apt_packages:
  - libmagick++-dev
  - texlive-latex-extra
  
before_install:
  - tlmgr install standalone

deploy:
  provider: script
  script: Rscript -e 'pkgdown::build_favicon(); pkgdown::deploy_site_github()'
  skip_cleanup: true
